services:

  laravel-docker:
    container_name: fleetmastr-docker
    build: .
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 9000:80
  
  mysql_db:
    image: mysql:7.5.38
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fleetmastr_docker
    ports:
    - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin:7.1.0
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
