version: '3'
services:
  
  # PHP Service
    php:
        build:
            context: .
            target: app
            args:
                - APP_ENV=${APP_ENV}
                
        environment:
            - APP_ENV=local
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - mysql_db

  # Database server
    mysql_db:
        image: mysql:5.7.38
        environment:
           - MYSQL_DATABASE=firstmile_fleetmastr
           - MYSQL_USER=root
           - MYSQL_PASSWORD=${DB_PASSWORD}
           - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:        
           - db-data:/var/lib/mysql
        ports:
           - 3309:3306
  
   # Node Server
    node:
        build:
            context: .
            target: node
        volumes:
            - .:/usr/src
            - ./node_modules:/usr/src/node_modules
        tty: true

volumes:
    db-data: ~
