services:

 # web:
  #  image: qa1.fleetmastr.com:fleetdemo
  #  ports:
   #   - 9002:80


  laravel-docker:
    container_name: fleetmastr-docker
    build: .
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 9000:80
  
  mysql_db:
    image: mysql:5.7.38
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fleetmastr_docker
    ports:
    - 3309:3306
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
