var elixir = require('laravel-elixir');

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Sass
 | file for our application, as well as publishing vendor resources.
 |
 */

elixir(function(mix) {
    mix.browserify(
        'defects.js',
        'public/js/bundles/defects.bundle.js'
    );
    mix.browserify(
        'checks.js',
        'public/js/bundles/checks.bundle.js'
    );
    mix.browserify(
        'checks-create.js',
        'public/js/bundles/checks-create.bundle.js'
    );
    mix.browserify(
        'training.js',
        'public/js/bundles/training.bundle.js'
    );
    mix.browserify(
        'telematics.js',
        'public/js/bundles/telematics.bundle.js'
    );

    mix.sass('clh_branding.scss');
    mix.sass('yorkshirewater_branding.scss');
    mix.sass('thames_branding.scss');
    mix.sass('lanes_branding.scss');
    mix.sass('clh_pdf_branding.scss');
    mix.sass('thames_pdf_branding.scss');
    mix.sass('lanes_pdf_branding.scss');
    mix.sass('yorkshirewater_pdf_branding.scss');

    mix.copy('./public/img', './public/build/img');
    mix.copy('./public/fonts', './public/build/fonts');
    mix.copy('./public/js/tinymce/langs', './public/build/js/tinymce/langs');
    mix.copy('./public/js/tinymce/plugins', './public/build/js/tinymce/plugins');
    mix.copy('./public/js/tinymce/skins', './public/build/js/tinymce/skins');
    mix.copy('./public/js/tinymce/themes', './public/build/js/tinymce/themes');
    mix.copy('./public/css/colorpicker/images', './public/build/css/colorpicker/images');

    mix.version([
        'public/css/simple-line-icons.min.css',
        'public/css/bootstrap.min.css',
        'public/css/uniform.default.css',
        'public/css/bootstrap-switch.min.css',
        'public/css/toastr/toastr.min.css',
        'public/css/datepicker/bootstrap-datepicker3.css',
        'public/css/jqgrid/ui.jqgrid-bootstrap.css',
        'public/css/select2/select2.css',
        'public/css/datetimepicker/bootstrap-datetimepicker.min.css',
        'public/css/colorpicker/jquery.colorpicker.css',
        'public/css/components-md.css',
        'public/css/plugins-md.css',
        'public/css/layout.css',
        'public/css/grey.css',
        'public/css/timeline.css',
        'public/css/weather.css',
        'public/css/new_color.css',
        'public/css/jobviewer-font.css',
        'public/css/ie7/ie7.css',
        'public/css/ie.css',
        'public/css/new_font/style.css',
        'public/css/theme-overrides.css',
        'public/css/jquery-ui-custom.css',
        'public/css/custom.css',
        'public/css/jqgrid-overrides.css',
        'public/js/jcrop/css/jquery.Jcrop.css',
        'public/css/brand/main.css',
        'public/css/login.css',
        'public/css/branding.css',
        'public/css/lightbox.css',
        'public/css/bootstrap-daterangepicker/daterangepicker-bs3.css',
        'public/css/bootstrap-editable/bootstrap-editable/css/bootstrap-editable.css',
        'public/css/bootstrap-editable/inputs-ext/address/address.css',
        'public/css/jasny-bootstrap.min.css',
        'public/css/bootstrap-modal/bootstrap-modal-bs3patch.css',
        'public/css/bootstrap-modal/bootstrap-modal.css',
        'public/css/fullcalendar.min.css',
        'public/css/fleet-calendar.css',
        'public/css/jquery-file-upload/jquery.fileupload.css',
        'public/css/jquery-file-upload/jquery.fileupload-ui.css',
        'public/css/jquery-file-upload/jquery.fileupload-noscript.css',
        'public/css/jquery-file-upload/jquery.fileupload-ui-noscript.css',
        'public/css/datepicker/bootstrap-datepicker.standalone.min.css',
        'public/css/datepicker/bootstrap-datepicker3.standalone.min.css',
        'public/css/chart.css',
        'public/css/cropper.css',
        'public/css/jquery-ui-1-12-1.css',
        'public/css/telematics.css',
        'public/css/vanilla-datetimerange-picker/vanilla-datetimerange-picker.css',
        'public/css/pdf-font.min.css',
        'public/css/brand/pdf.css',
        'public/js/jquery.min.js',
        'public/js/jquery-migrate.min.js',
        'public/js/jquery-ui.min.js',
        'public/js/bootstrap.min.js',
        'public/js/bootstrap-hover-dropdown.min.js',
        'public/js/jquery.slimscroll.min.js',
        'public/js/jquery.blockui.min.js',
        'public/js/jquery.cokie.min.js',
        'public/js/jquery.uniform.min.js',
        'public/js/moment.min.js',
        'public/js/bootstrap-switch.min.js',
        'public/js/datepicker/bootstrap-datepicker.min.js',
        'public/js/toastr/toastr.min.js',
        'public/js/jqgrid/jquery.jqGrid.min.js',
        'public/js/jqgrid/plugins/grid.setcolumns.js',
        'public/js/select2/select2.js',
        'public/js/colorpicker/jquery.colorpicker.js',
        'public/js/jcrop/js/jquery.Jcrop.js',
        'public/js/jqgrid/i18n/grid.locale-en.js',
        'public/js/metronic.js',
        'public/js/layout.js',
        'public/js/demo.js',
        'public/js/datetimepicker/bootstrap-datetimepicker.min.js',
        'public/js/datetimepicker/quick-sidebar.js',
        'public/js/bootbox/bootbox.min.js',
        'public/js/jquery-validation/jquery.validate.min.js',
        'public/js/jquery-validation/additional-methods.min.js',
        'public/js/weather/openWeather.min.js',
        'public/js/weather/weather.js',
        'public/js/own-custom.js',
        'public/js/jquery.validate.min.js',
        'public/js/login.js',
        'public/js/lightbox.min.js',
        'public/js/bundles/checks-create.bundle.js',
        'public/js/bootstrap-daterangepicker/daterangepicker.js',
        'public/js/jqgrid/jquery.jqGridHelper.js',
        'public/js/checks.js',
        'public/js/bundles/checks.bundle.js',
        'public/js/exif/exif.js',
        'public/js/checklocation.js',
        'public/js/jquery-easypiechart/jquery.easypiechart.min.js',
        'public/js/flot/jquery.flot.min.js',
        'public/js/flot/jquery.flot.resize.min.js',
        'public/js/flot/jquery.flot.pie.min.js',
        'public/js/flot/jquery.flot.tooltip.min.js',
        'public/js/flot/jquery.flot.valuelabels.js',
        'public/js/flot/jquery.flot.categories.min.js',
        'public/js/dashboard.js',
        'public/js/canvasjs/jquery.canvasjs.min.js',
        'public/js/bundles/telematics.bundle.js',
        'public/js/bundles/defects.bundle.js',
        'public/js/defects.js',
        'public/js/jquery.mockjax.js',
        'public/js/bootstrap-editable/bootstrap-editable/js/bootstrap-editable.js',
        'public/js/bootstrap-editable/inputs-ext/address/address.js',
        'public/js/form-editable.js',
        'public/js/jasny-bootstrap.min.js',
        'public/js/incidents.js',
        'public/js/bootstrap-modal/bootstrap-modal.js',
        'public/js/bootstrap-modal/bootstrap-modalmanager.js',
        'public/js/tinymce/tinymce.js',
        'public/js/tinymce/jquery.tinymce.min.js',
        'public/js/messages-jqgrid.js',
        'public/js/dropzone.js',
        'public/js/flow/flow.js',
        'public/js/bundles/training.bundle.js',
        'public/js/fullcalendar.min.js',
        'public/js/planner.js',
        'public/js/reports.js',
        'public/js/settings.js',
        'public/js/users.js',
        'public/js/user_vehicle_history.js',
        'public/js/user_vehicle_private_use.js',
        'public/js/jquery-file-upload/jquery.ui.widget.js',
        'public/js/jquery-file-upload/tmpl.min.js',
        'public/js/jquery-file-upload/load-image.min.js',
        'public/js/jquery-file-upload/canvas-to-blob.min.js',
        'public/js/blueimp-gallery/jquery.blueimp-gallery.min.js',
        'public/js/jquery-file-upload/jquery.iframe-transport.js',
        'public/js/jquery-file-upload/jquery.fileupload.js',
        'public/js/jquery-file-upload/jquery.fileupload-process.js',
        'public/js/jquery-file-upload/jquery.fileupload-image.js',
        'public/js/jquery-file-upload/jquery.fileupload-audio.js',
        'public/js/jquery-file-upload/jquery.fileupload-video.js',
        'public/js/jquery-file-upload/jquery.fileupload-validate.js',
        'public/js/jquery-file-upload/jquery.fileupload-ui.js',
        'public/js/vehicles-repeater-elements.js',
        'public/js/vehicles-add.js',
        'public/js/vehicle-doc-upload.js',
        'public/js/vehicles.js',
        'public/js/vehicles_planning.js',
        'public/js/types.js',
        'public/js/datatable/select2.min.js',
        'public/js/workshop_user.js',
        'public/js/repeater.js',
        'public/js/datepicker/bootstrap-datepicker-1.9.0.min.js',
        'public/js/chart.js',
        'public/js/cropper.js',
        'public/js/jquery-cropper.js',
        'public/js/jquery-ui-1-12-1.js',
        'public/js/vehicle-maintenance-history.js',
        'public/js/company.js',
        'public/js/company-edit.js',
        'public/js/custom-datepicker-auto-format.js',
        'public/js/dvsa.js',
        'public/js/alert_notifications.js',
        'public/js/report_categories.js',
        'public/js/custom-reports.js',
        'public/js/customreports-jqgrid.js',
        'public/js/custom-report-calendar.js',
        'public/js/message-custom.js',
        'public/js/tinymce_acknowledgement_plugin.js',
        'public/js/alert_centres.js',
        'public/js/alert_settings.js',
        'public/js/vehicle-document-upload.js',
        'public/js/vehicle_documents.js',
        'public/js/vanilla-datetimerange-picker/vanilla-datetimerange-picker.js',
        'public/js/telematics_behaviour.js',
        'public/js/telematics_vehicles.js',
        'public/js/telematics-front.js',
        'public/js/telematics_journeys.js',
        'public/js/telematics_locations.js',
        'public/js/telematics_incidents.js',
        'public/js/telematics_zones.js',
        'public/js/telematics_zone_alerts.js',
        'public/js/vehicle_insurance.js'
    ]);
});