UPDATE `defect_master` SET `order`=`order`+2 WHERE `order`>1;

INSERT INTO `defect_master` (`order`, `page_title`, `app_question`, `app_question_with_defect`, `defect`, `has_image`, `has_text`, `is_prohibitional`, `safety_notes`, `for_hgv`, `for_non-hgv`) VALUES ('2', 'Reversing camera system', 'Is the reversing camera system free from defects?', 'Is the reversing camera system free from additional defects?', 'Rear camera inoperative', '1', '0', '0', 'Roadworthy but needs workshop visit', '1', '1');
INSERT INTO `defect_master` (`order`, `page_title`, `app_question`, `app_question_with_defect`, `defect`, `has_image`, `has_text`, `is_prohibitional`, `safety_notes`, `for_hgv`, `for_non-hgv`) VALUES ('2', 'Reversing camera system', 'Is the reversing camera system free from defects?', 'Is the reversing camera system free from additional defects?', 'Reversing monitor inoperative', '1', '0', '0', 'Roadworthy but needs workshop visit', '1', '1');

INSERT INTO `defect_master` (`order`, `page_title`, `app_question`, `app_question_with_defect`, `defect`, `has_image`, `has_text`, `is_prohibitional`, `safety_notes`, `for_hgv`, `for_non-hgv`) VALUES ('3', 'Telematics system', 'Is the Masternaught telematics system free from defects?', 'Is the Masternaught telematics system free from additional defects?', 'Driver feedback bar faulty', '0', '0', '0', 'Roadworthy but needs workshop visit', '1', '1');
INSERT INTO `defect_master` (`order`, `page_title`, `app_question`, `app_question_with_defect`, `defect`, `has_image`, `has_text`, `is_prohibitional`, `safety_notes`, `for_hgv`, `for_non-hgv`) VALUES ('3', 'Telematics system', 'Is the Masternaught telematics system free from defects?', 'Is the Masternaught telematics system free from additional defects?', 'Driver feedback bar damaged', '0', '0', '0', 'Roadworthy but needs workshop visit', '1', '1');
INSERT INTO `defect_master` (`order`, `page_title`, `app_question`, `app_question_with_defect`, `defect`, `has_image`, `has_text`, `is_prohibitional`, `safety_notes`, `for_hgv`, `for_non-hgv`) VALUES ('3', 'Telematics system', 'Is the Masternaught telematics system free from defects?', 'Is the Masternaught telematics system free from additional defects?', 'No power to driver feedback bar', '0', '0', '0', 'Roadworthy but needs workshop visit', '1', '1');
INSERT INTO `defect_master` (`order`, `page_title`, `app_question`, `app_question_with_defect`, `defect`, `has_image`, `has_text`, `is_prohibitional`, `safety_notes`, `for_hgv`, `for_non-hgv`) VALUES ('3', 'Telematics system', 'Is the Masternaught telematics system free from defects?', 'Is the Masternaught telematics system free from additional defects?', 'Driver fob lost', '0', '0', '0', 'Roadworthy but needs workshop visit', '1', '1');
INSERT INTO `defect_master` (`order`, `page_title`, `app_question`, `app_question_with_defect`, `defect`, `has_image`, `has_text`, `is_prohibitional`, `safety_notes`, `for_hgv`, `for_non-hgv`) VALUES ('3', 'Telematics system', 'Is the Masternaught telematics system free from defects?', 'Is the Masternaught telematics system free from additional defects?', 'Driver fob damaged', '0', '0', '0', 'Roadworthy but needs workshop visit', '1', '1');
INSERT INTO `defect_master` (`order`, `page_title`, `app_question`, `app_question_with_defect`, `defect`, `has_image`, `has_text`, `is_prohibitional`, `safety_notes`, `for_hgv`, `for_non-hgv`) VALUES ('3', 'Telematics system', 'Is the Masternaught telematics system free from defects?', 'Is the Masternaught telematics system free from additional defects?', 'Driver fob faulty', '0', '0', '0', 'Roadworthy but needs workshop visit', '1', '1');
