<?php 

return [
    'name' => env('BRAND_NAME'),
    /**
     * The common varialbes for all the brands.
     */
    'common' => [
        
    ],
    /**
     * The variables specific to Thames Water brand.
     */
    'thames' => [
        'title' => 'fleetmastr',
        'brand_title' => '<strong>fleet</strong>mastr',
        'brand_product_name' => 'fleet',
        'brand_product_name_part2' => 'mastr',
        'primary_colour' => '#47A6DB',
        'stylesheet' => '/css/thames_branding.css',
        'pdf_stylesheet' => '/css/thames_pdf_branding.css',
        'logo' => [
            'transparent' => '/img/logo/fleetmastr1.png',
            'colored' => '/img/logo/fleetmastr2.png',
            'footer_logo' => '/img/logo/lanes-group-logo-footer.png',
            'pdf_logo' => '/img/logo/fleetmastr1.png',
            'fleet_logo' => '/img/logo/fleet_master_white.png',
            'fleet_logo_for_email' => '/img/logo/fleetmastr-grey.png',
            'email_logo'=> '/img/logo/fleetmastr1.png',
            'auth_logo' => '/img/logo/logo_with_white_title_fm.png'
        ],        
        'brand_name' => 'Thames Water',
        'account_name' => '<b>fleet</b>mastr',
        'footer_text' => 'developed by',
        'footer_text_part2' => '<strong>i</strong>mastr',
        'pdf_title_name' => 'Thames',
        'email_logo_width' => '80px',
        'import_email_subject_prefix' => 'Thames Water',
    ],
    /**
     * The variables specific to CLH.
     */
    'clh' => [
        'title' => 'CLH fleetmastr',
        'brand_title' => '<strong>fleet</strong>mastr',
        'brand_product_name' => 'fleet',
        'brand_product_name_part2' => 'mastr',
        'primary_colour' => '#407EC9',
        'stylesheet' => '/css/clh_branding.css',
        'pdf_stylesheet' => '/css/clh_pdf_branding.css',
        'logo' => [
            'transparent' => '/img/logo/logo_clh_border.svg',
            'colored' => '/img/logo/logo_clh_border.svg',
            'footer_logo' => '/img/logo/lanes-group-logo-footer.png',
            'pdf_logo' => '/img/logo/logo_clh.png',
            'fleet_logo' => '/img/logo/fleet_master_white.png',
            'fleet_logo_for_email' => '/img/logo/fleetmastr-grey.png',
            'email_logo'=> '/img/logo/logo_clh.png',
            'auth_logo' => '/img/logo/logo_clh_border.svg'
        ],        
        'brand_name' => 'Thames Water',
        'account_name' => '<b>fleet</b>mastr',
        'footer_text' => 'developed by',
        'footer_text_part2' => '<strong>i</strong>mastr',
        'pdf_title_name' => 'Thames',
        'email_logo_width' => '80px',
        'import_email_subject_prefix' => 'CLH',
    ],
    /**
     * The variables specific to Yorkshire Water brand.
     */
    'yorkshirewater' => [
        'title' => 'Yorkshire Water fleetmastr',
        'brand_title' => '<strong>fleet</strong>mastr',
        'brand_product_name' => 'fleet',
        'brand_product_name_part2' => 'mastr',
        'primary_colour' => '#20a1c9',
        'stylesheet' => '/css/yorkshirewater_branding.css',
        'pdf_stylesheet' => '/css/yorkshirewater_pdf_branding.css',
        'logo' => [
            'transparent' => '/img/logo/yw_white.png',
            'colored' => '/img/logo/yw_white.png',
            'footer_logo' => '/img/logo/lanes-group-logo-footer.png',
            'pdf_logo' => '/img/logo/colored_yw.png',
            'fleet_logo' => '/img/logo/fleet_master_white.png',
            'fleet_logo_for_email' => '/img/logo/fleetmastr-grey.png',
            'email_logo'=> '/img/logo/colored_yw.png',
            'auth_logo' => '/img/logo/yw_white.png'
        ],        
        'brand_name' => 'Thames Water',
        'account_name' => '<b>fleet</b>mastr',
        'footer_text' => 'developed by',
        'footer_text_part2' => '<strong>i</strong>mastr',
        'pdf_title_name' => 'Thames',
        'email_logo_width' => '140pt',
        'import_email_subject_prefix' => 'Yorkshire Water',
    ],
    /**
     * The variables specific to First Mile brand.
     */
    'firstmile' => [
        'title' => 'First Mile fleetmastr',
        'brand_title' => '<strong>fleet</strong>mastr',
        'brand_product_name' => 'fleet',
        'brand_product_name_part2' => 'mastr',
        'primary_colour' => '#00AFAF',
        'stylesheet' => '/css/firstmile_branding.css',
        'pdf_stylesheet' => '/css/firstmile_pdf_branding.css',
        'logo' => [
            'transparent' => '/img/logo/first_mile.jpg',
            'colored' => '/img/logo/first_mile.jpg',
            'footer_logo' => '/img/logo/lanes-group-logo-footer.png',
            'pdf_logo' => '/img/logo/colored_yw.png',
            'fleet_logo' => '/img/logo/fleet_master_white.png',
            'fleet_logo_for_email' => '/img/logo/fleetmastr-grey.png',
            'email_logo'=> '/img/logo/colored_yw.png',
            'auth_logo' => '/img/logo/first_mile.jpg'
        ],        
        'brand_name' => 'first mile',
        'account_name' => '<b>fleet</b>mastr',
        'footer_text' => 'developed by',
        'footer_text_part2' => '<strong>i</strong>mastr',
        'pdf_title_name' => 'first mile',
        'email_logo_width' => '140pt',
        'import_email_subject_prefix' => 'First Mile',
    ],
    /**
     * The variables specific to tRiio brand.
     */
    'triio' => [
        'title' => 'tRIIO fleetmastr',
        'brand_title' => '<strong>fleet</strong>mastr',
        'brand_product_name' => 'fleet',
        'brand_product_name_part2' => 'mastr',
        'primary_colour' => '#00B0E0',
        'stylesheet' => '/css/triio_branding.css',
        'pdf_stylesheet' => '/css/triio_pdf_branding.css',
        'logo' => [
            'transparent' => '/img/logo/triio.png',
            'colored' => '/img/logo/triio.png',
            'footer_logo' => '/img/logo/lanes-group-logo-footer.png',
            'pdf_logo' => '/img/logo/colored_yw.png',
            'fleet_logo' => '/img/logo/fleet_master_white.png',
            'fleet_logo_for_email' => '/img/logo/fleetmastr-grey.png',
            'email_logo'=> '/img/logo/colored_yw.png',
            'auth_logo' => '/img/logo/triio.png'
        ],        
        'brand_name' => 'tRIIO',
        'account_name' => '<b>fleet</b>mastr',
        'footer_text' => 'developed by',
        'footer_text_part2' => '<strong>i</strong>mastr',
        'pdf_title_name' => 'tRIIO',
        'email_logo_width' => '140pt',
        'import_email_subject_prefix' => 'tRIIO',
    ],

    'skanska' => [
        'title' => 'SKANSKA fleetmastr',
        'brand_title' => '<strong>fleet</strong>mastr',
        'brand_product_name' => 'fleet',
        'brand_product_name_part2' => 'mastr',
        'primary_colour' => '#0078c9',
        // 'stylesheet' => '/css/triio_branding.css',
        // 'pdf_stylesheet' => '/css/triio_pdf_branding.css',
        'logo' => [
            // 'transparent' => '/img/logo/triio.png',
            // 'colored' => '/img/logo/triio.png',
            'footer_logo' => '/img/logo/lanes-group-logo-footer.png',
            // 'pdf_logo' => '/img/logo/colored_yw.png',
            'fleet_logo' => '/img/logo/fleet_master_white.png',
            'fleet_logo_for_email' => '/img/logo/fleetmastr-grey.png',
            // 'email_logo'=> '/img/logo/colored_yw.png',
            // 'auth_logo' => '/img/logo/triio.png'
        ],
        'brand_name' => 'SKANSKA',
        'account_name' => '<b>fleet</b>mastr',
        'footer_text' => 'developed by',
        'footer_text_part2' => '<strong>i</strong>mastr',
        'pdf_title_name' => 'SKANSKA',
        'email_logo_width' => '140pt',
        'import_email_subject_prefix' => 'Skanska',
        'import_email_subject_prefix' => 'SKANSKA',
    ],

    'icl' => [
        'title' => 'ICL fleetmastr',
        'brand_title' => '<strong>fleet</strong>mastr',
        'brand_product_name' => 'fleet',
        'brand_product_name_part2' => 'mastr',
        'primary_colour' => '#1f355e',
        // 'stylesheet' => '/css/icl_branding.css',
        // 'pdf_stylesheet' => '/css/icl_pdf_branding.css',
        'logo' => [
            // 'transparent' => '/img/logo/fleetmastr1.png',
            // 'colored' => '/img/logo/fleetmastr2.png',
            'footer_logo' => '/img/logo/lanes-group-logo-footer.png',
            // 'pdf_logo' => '/img/logo/fleetmastr1.png',
            'fleet_logo' => '/img/logo/fleet_master_white.png',
            'fleet_logo_for_email' => '/img/logo/fleetmastr-grey.png',
            // 'email_logo'=> '/img/logo/fleetmastr1.png',
            // 'auth_logo' => '/img/logo/logo_with_white_title_fm.png'
        ],        
        'brand_name' => 'ICL',
        'account_name' => '<b>fleet</b>mastr',
        'footer_text' => 'developed by',
        'footer_text_part2' => '<strong>i</strong>mastr',
        'pdf_title_name' => 'ICL',
        'email_logo_width' => '80px',
        'import_email_subject_prefix' => 'ICL',
    ],

    'ferns' => [
        'title' => 'Ferns fleetmastr',
        'brand_title' => '<strong>fleet</strong>mastr',
        'brand_product_name' => 'fleet',
        'brand_product_name_part2' => 'mastr',
        'primary_colour' => '#1f355e',
        // 'stylesheet' => '/css/icl_branding.css',
        // 'pdf_stylesheet' => '/css/icl_pdf_branding.css',
        'logo' => [
            // 'transparent' => '/img/logo/fleetmastr1.png',
            // 'colored' => '/img/logo/fleetmastr2.png',
            'footer_logo' => '/img/logo/lanes-group-logo-footer.png',
            // 'pdf_logo' => '/img/logo/fleetmastr1.png',
            'fleet_logo' => '/img/logo/fleet_master_white.png',
            'fleet_logo_for_email' => '/img/logo/fleetmastr-grey.png',
            // 'email_logo'=> '/img/logo/fleetmastr1.png',
            // 'auth_logo' => '/img/logo/logo_with_white_title_fm.png'
        ],        
        'brand_name' => 'FERNS',
        'account_name' => '<b>fleet</b>mastr',
        'footer_text' => 'developed by',
        'footer_text_part2' => '<strong>i</strong>mastr',
        'pdf_title_name' => 'FERNS',
        'email_logo_width' => '80px',
        'import_email_subject_prefix' => 'Ferns fleetmastr',
    ],
    'mgroupservices' => [
        'title' => 'M Group Services fleetmastr',
        'brand_title' => '<strong>fleet</strong>mastr',
        'brand_product_name' => 'fleet',
        'brand_product_name_part2' => 'mastr',
        'primary_colour' => '#ef3e42',
        // 'stylesheet' => '/css/triio_branding.css',
        // 'pdf_stylesheet' => '/css/triio_pdf_branding.css',
        'logo' => [
            // 'transparent' => '/img/logo/triio.png',
            // 'colored' => '/img/logo/triio.png',
            'footer_logo' => '/img/logo/lanes-group-logo-footer.png',
            // 'pdf_logo' => '/img/logo/colored_yw.png',
            'fleet_logo' => '/img/logo/fleet_master_white.png',
            'fleet_logo_for_email' => '/img/logo/fleetmastr-grey.png',
            // 'email_logo'=> '/img/logo/colored_yw.png',
            // 'auth_logo' => '/img/logo/triio.png'
        ],
        'brand_name' => 'M Group Services fleetmastr',
        'account_name' => '<b>fleet</b>mastr',
        'footer_text' => 'developed by',
        'footer_text_part2' => '<strong>i</strong>mastr',
        'pdf_title_name' => 'M Group Services fleetmastr',
        'email_logo_width' => '140pt',
        'import_email_subject_prefix' => 'M Group Services',
    ],
    /**
     * The variables specific to Exolum.
     */
    'exolum' => [
        'title' => 'Exolum fleetmastr',
        'brand_title' => '<strong>fleet</strong>mastr',
        'brand_product_name' => 'fleet',
        'brand_product_name_part2' => 'mastr',
        'primary_colour' => '#84BD00',
        'stylesheet' => '/css/exolum_branding.css',
        'pdf_stylesheet' => '/css/exolum_pdf_branding.css',
        'logo' => [
            'transparent' => '/img/logo/logo_exolum_border.svg',
            'colored' => '/img/logo/logo_exolum_border.svg',
            'footer_logo' => '/img/logo/lanes-group-logo-footer.png',
            'pdf_logo' => '/img/logo/logo_exolum.png',
            'fleet_logo' => '/img/logo/fleet_master_white.png',
            'fleet_logo_for_email' => '/img/logo/fleetmastr-grey.png',
            'email_logo'=> '/img/logo/logo_exolum.png',
            'auth_logo' => '/img/logo/logo_exolum_border.svg'
        ],        
        'brand_name' => 'Thames Water',
        'account_name' => '<b>fleet</b>mastr',
        'footer_text' => 'developed by',
        'footer_text_part2' => '<strong>i</strong>mastr',
        'pdf_title_name' => 'Thames',
        'email_logo_width' => '80px',
        'import_email_subject_prefix' => 'Exolum',
    ],
    'rps' => [
        'title' => 'RPS fleetmastr',
        'brand_title' => '<strong>fleet</strong>mastr',
        'brand_product_name' => 'fleet',
        'brand_product_name_part2' => 'mastr',
        'primary_colour' => '#71004b',
        'stylesheet' => '/css/exolum_branding.css',
        'pdf_stylesheet' => '/css/exolum_pdf_branding.css',
        'logo' => [
            'transparent' => '/img/logo/rps.jpg',
            'colored' => '/img/logo/rps.jpg',
            'footer_logo' => '/img/logo/lanes-group-logo-footer.png',
            'pdf_logo' => '/img/logo/rps.jpg',
            'fleet_logo' => '/img/logo/fleet_master_white.png',
            'fleet_logo_for_email' => '/img/logo/fleetmastr-grey.png',
            'email_logo'=> '/img/logo/rps.jpg',
            'auth_logo' => '/img/logo/rps.jpg'
        ],        
        'brand_name' => 'Thames Water',
        'account_name' => '<b>fleet</b>mastr',
        'footer_text' => 'developed by',
        'footer_text_part2' => '<strong>i</strong>mastr',
        'pdf_title_name' => 'Thames',
        'email_logo_width' => '80px',
        'import_email_subject_prefix' => 'RPS',
    ],

    'hjleaoakes' => [
        'title' => 'HJ Lea Oakes fleetmastr',
        'brand_title' => '<strong>fleet</strong>mastr',
        'brand_product_name' => 'fleet',
        'brand_product_name_part2' => 'mastr',
        'primary_colour' => '#118243',
        'stylesheet' => '/css/hjleaoakes_branding.css',
        'pdf_stylesheet' => '/css/hjleaoakes_pdf_branding.css',
        'logo' => [
            'transparent' => '/img/logo/hjleaoakes.jpg',
            'colored' => '/img/logo/hjleaoakes.jpg',
            'footer_logo' => '/img/logo/lanes-group-logo-footer.png',
            'pdf_logo' => '/img/logo/hjleaoakes.jpg',
            'fleet_logo' => '/img/logo/fleet_master_white.png',
            'fleet_logo_for_email' => '/img/logo/fleetmastr-grey.png',
            'email_logo'=> '/img/logo/hjleaoakes.jpg',
            'auth_logo' => '/img/logo/hjleaoakes.jpg'
        ],
        'brand_name' => 'HJ Lea Oakes',
        'account_name' => '<b>fleet</b>mastr',
        'footer_text' => 'developed by',
        'footer_text_part2' => '<strong>i</strong>mastr',
        'pdf_title_name' => 'HJLeaOakes',
        'email_logo_width' => '80px',
        'import_email_subject_prefix' => 'HJ Lea Oakes',
    ],

    'servicemetals' => [
        'title' => 'Service Metals fleetmastr',
        'brand_title' => '<strong>fleet</strong>mastr',
        'brand_product_name' => 'fleet',
        'brand_product_name_part2' => 'mastr',
        'primary_colour' => '#1e3e72',
        // 'stylesheet' => '/css/icl_branding.css',
        // 'pdf_stylesheet' => '/css/icl_pdf_branding.css',
        'logo' => [
            // 'transparent' => '/img/logo/fleetmastr1.png',
            // 'colored' => '/img/logo/fleetmastr2.png',
            'footer_logo' => '/img/logo/lanes-group-logo-footer.png',
            // 'pdf_logo' => '/img/logo/fleetmastr1.png',
            'fleet_logo' => '/img/logo/fleet_master_white.png',
            'fleet_logo_for_email' => '/img/logo/fleetmastr-grey.png',
            // 'email_logo'=> '/img/logo/fleetmastr1.png',
            // 'auth_logo' => '/img/logo/logo_with_white_title_fm.png'
        ],        
        'brand_name' => 'Service Metals',
        'account_name' => '<b>fleet</b>mastr',
        'footer_text' => 'developed by',
        'footer_text_part2' => '<strong>i</strong>mastr',
        'pdf_title_name' => 'Service Metals',
        'email_logo_width' => '80px',
        'import_email_subject_prefix' => 'Service Metals',
    ],

    'chanlon' => [
        'title' => 'Chanlon Group fleetmastr',
        'brand_title' => '<strong>fleet</strong>mastr',
        'brand_product_name' => 'fleet',
        'brand_product_name_part2' => 'mastr',
        'primary_colour' => '#036fb8',
        // 'stylesheet' => '/css/icl_branding.css',
        // 'pdf_stylesheet' => '/css/icl_pdf_branding.css',
        'logo' => [
            // 'transparent' => '/img/logo/fleetmastr1.png',
            // 'colored' => '/img/logo/fleetmastr2.png',
            'footer_logo' => '/img/logo/lanes-group-logo-footer.png',
            // 'pdf_logo' => '/img/logo/fleetmastr1.png',
            'fleet_logo' => '/img/logo/fleet_master_white.png',
            'fleet_logo_for_email' => '/img/logo/fleetmastr-grey.png',
            // 'email_logo'=> '/img/logo/fleetmastr1.png',
            // 'auth_logo' => '/img/logo/logo_with_white_title_fm.png'
        ],
        'brand_name' => 'Chanlon Group',
        'account_name' => '<b>fleet</b>mastr',
        'footer_text' => 'developed by',
        'footer_text_part2' => '<strong>i</strong>mastr',
        'pdf_title_name' => 'Chanlon Group',
        'email_logo_width' => '80px',
        'import_email_subject_prefix' => 'Chanlon Group',

    ],

    'fnf' => [
        'title' => 'Find and Finance fleetmastr',
        'brand_title' => '<strong>fleet</strong>mastr',
        'brand_product_name' => 'fleet',
        'brand_product_name_part2' => 'mastr',
        'primary_colour' => '#134371',
        // 'stylesheet' => '/css/icl_branding.css',
        // 'pdf_stylesheet' => '/css/icl_pdf_branding.css',
        'logo' => [
            // 'transparent' => '/img/logo/fleetmastr1.png',
            // 'colored' => '/img/logo/fleetmastr2.png',
            'footer_logo' => '/img/logo/lanes-group-logo-footer.png',
            // 'pdf_logo' => '/img/logo/fleetmastr1.png',
            'fleet_logo' => '/img/logo/fleet_master_white.png',
            'fleet_logo_for_email' => '/img/logo/fleetmastr-grey.png',
            // 'email_logo'=> '/img/logo/fleetmastr1.png',
            // 'auth_logo' => '/img/logo/logo_with_white_title_fm.png'
        ],        
        'brand_name' => 'Find and Finance',
        'account_name' => '<b>fleet</b>mastr',
        'footer_text' => 'developed by',
        'footer_text_part2' => '<strong>i</strong>mastr',
        'pdf_title_name' => 'Find and Finance',
        'email_logo_width' => '80px',
        'import_email_subject_prefix' => 'Find and Finance',
    ],

];
