<?php

return [

    'vehicleSubCategoriesNonHGV' => [
        '' => '',
        'car' => 'Car',
    	'LCV' => 'LCV',
        'none' => 'None',
    	'PCV' => 'PCV',
    	'Van' => 'Van',
    ],

    'vehicleDivisions' => [
        'FS Bristol Schools' => 'FS Bristol Schools',
        'FS City of London' => 'FS City of London',
        'FS Essex Schools' => 'FS Essex Schools',
        'FS Kent' => 'FS Kent',
        'FS Northwood' => 'FS Northwood',
        'FS Scotland' => 'FS Scotland',
        'FS Woking' => 'FS Woking',
        'HS Cambridgeshire' => 'HS Cambridgeshire',
        'HS Devon' => 'HS Devon',
        'HS Hampshire' => 'HS Hampshire',
        'HS Hinkley Point' => 'HS Hinkley Point',
        'HS North Somerset' => 'HS North Somerset',
        'HS Oxfordshire' => 'HS Oxfordshire',
        'HS Peterborough' => 'HS Peterborough',
        'HS Somerset' => 'HS Somerset',
        'INF A428' => 'INF A428',
        'IS Rail' => 'IS Rail',
        'IS Street Lighting Gloucester' => 'IS Street Lighting Gloucester',
        'IS Street Lighting Merrow O&M' => 'IS Street Lighting Merrow O&M',
        'IS Street Lighting Merrow External' => 'IS Street Lighting Merrow External',
        'IS Street Lighting Redbridge' => 'IS Street Lighting Redbridge',
        'IS Street Lighting South Croydon' => 'IS Street Lighting South Croydon',
    ],
    
    'vehicleRegions' => [
        'FS Bristol Schools' => ['Bristol' => 'Bristol'],
        'FS City of London' => ['City of London' => 'City of London'],
        'FS Essex Schools' => ['Essex' => 'Essex'],
        'FS Kent' => ['East Kent' => 'East Kent', 'Kent' => 'Kent', 'West Kent' => 'West Kent'],
        'FS Northwood' => ['Northwood' => 'Northwood'],
        'FS Scotland' => ['Motherwell' => 'Motherwell'],
        'FS Woking' => ['Woking' => 'Woking'],
        'HS Cambridgeshire' => ['Cambridge' => 'Cambridge', 'Ely' => 'Ely', 'Huntingdon' => 'Huntingdon', 'March' => 'March', 'Whittlesford' => 'Whittlesford'],
        'HS Devon' => ['Avocet Road' => 'Avocet Road', 'Copstone' => 'Copstone', 'Crediton' => 'Crediton', 'Dolton' => 'Dolton', 'Heron Road' => 'Heron Road', 'Honiton' => 'Honiton', 'Ivybridge' => 'Ivybridge', 'Kingsteignton' => 'Kingsteignton', 'Merton' => 'Merton', 'Okehampton' => 'Okehampton', 'Parracombe' => 'Parracombe', 'Rydon Quarry' => 'Rydon Quarry', 'South Molton' => 'South Molton', 'Tavistock' => 'Tavistock', 'Tiverton' => 'Tiverton', 'Torr' => 'Torr', 'Torrington' => 'Torrington'],

        'HS Hampshire' => ['Andover' => 'Andover', 'Bishops Waltham' => 'Bishops Waltham', 'Broadmarsh' => 'Broadmarsh', 'Hook' => 'Hook', 'Petersfield' => 'Petersfield', 'Totton' => 'Totton'],
        'HS Hinkley Point' => ['Hinkley Point' => 'Hinkley Point'],
        'HS North Somerset' => ['Sandford' => 'Sandford'],
        'HS Oxfordshire' => ['Deddington' => 'Deddington', 'Drayton' => 'Drayton', 'Milton Common' => 'Milton Common', 'Oxford' => 'Oxford', 'Woodcote' => 'Woodcote'],
        'HS Peterborough' => ['Peterborough' => 'Peterborough'],
        'HS Somerset' => ['Dunball' => 'Dunball', 'Exford' => 'Exford', 'Frome' => 'Frome', 'Glastonbury' => 'Glastonbury', 'Minehead' => 'Minehead', 'Priorswood' => 'Priorswood', 'Taunton' => 'Taunton', 'Yeovil' => 'Yeovil'],
        'INF A428' => ['A428' => 'A428'],
        'IS Rail'  => ['Snaresbrook' => 'Snaresbrook'],
        'IS Street Lighting Gloucester' => ['Gloucester' => 'Gloucester'],
        'IS Street Lighting Merrow O&M' => ['Merrow O&M' => 'Merrow O&M'],
        'IS Street Lighting Merrow External' => ['Merrow External' => 'Merrow External'],
        'IS Street Lighting Redbridge' => ['Redbridge' => 'Redbridge'],
        'IS Street Lighting South Croydon' => ['South Croydon' => 'South Croydon'],
    ],
   
    'usersDivisions' => [
        'FS Bristol Schools' => 'FS Bristol Schools',
        'FS City of London' => 'FS City of London',
        'FS Essex Schools' => 'FS Essex Schools',
        'FS Kent' => 'FS Kent',
        'FS Northwood' => 'FS Northwood',
        'FS Scotland' => 'FS Scotland',
        'FS Woking' => 'FS Woking',
        'HS Cambridgeshire' => 'HS Cambridgeshire',
        'HS Devon' => 'HS Devon',
        'HS Hampshire' => 'HS Hampshire',
        'HS Hinkley Point' => 'HS Hinkley Point',
        'HS North Somerset' => 'HS North Somerset',
        'HS Oxfordshire' => 'HS Oxfordshire',
        'HS Peterborough' => 'HS Peterborough',
        'HS Somerset' => 'HS Somerset',
        'INF A428' => 'INF A428',
        'IS Rail'  => 'IS Rail',
        'IS Street Lighting'=> 'IS Street Lighting',
    ],

    'userRegionsForSelect' => [
        'FS Bristol Schools' => ['FS Bristol Schools' => 'FS Bristol Schools'],
        'FS City of London' => ['FS City of London' => 'FS City of London'],
        'FS Essex Schools' => ['FS Essex Schools' => 'FS Essex Schools'],
        'FS Kent' => ['FS Kent' => 'FS Kent'],
        'FS Northwood' => ['FS Northwood' => 'FS Northwood'],
        'FS Scotland' => ['FS Scotland' => 'FS Scotland'],
        'FS Woking' => ['FS Woking' => 'FS Woking'],
        'HS Cambridgeshire' => ['HS Cambridgeshire' => 'HS Cambridgeshire'],
        'HS Devon' => ['HS Devon' => 'HS Devon'],
        'HS Hampshire' => ['HS Hampshire' => 'HS Hampshire'],
        'HS Hinkley Point' => ['HS Hinkley Point' => 'HS Hinkley Point'],
        'HS North Somerset' => ['HS North Somerset' => 'HS North Somerset'],
        'HS Oxfordshire' => ['HS Oxfordshire' => 'HS Oxfordshire'],
        'HS Peterborough' => ['HS Peterborough' => 'HS Peterborough'],
        'HS Somerset' => ['HS Somerset' => 'HS Somerset'],
        'INF A428' => ['INF A428' => 'INF A428'],
        'IS Rail'  => ['IS Rail' => 'IS Rail'],
        'IS Street Lighting'=> ['IS Street Lighting' => 'IS Street Lighting'],
    ],

    'usersBaseLocations' => [
        '' => '',
    ],

   'vehicleRegionsForSelect' => [
        'all' => 'All',
        'bl' => 'Bristol',
        'cl' => 'City of London',
        'ex' => 'Essex',
        'ek' => 'East Kent',
        'kt' => 'Kent',
        'wk' => 'West Kent',
        'nd' => 'Northwood',
        'ml' => 'Motherwell',
        'wg' => 'Woking',
        'ce' => 'Cambridge',
        'ey' => 'Ely',
        'hn' => 'Huntingdon',
        'mh' => 'March',
        'wd' => 'Whittlesford',
        'ar' => 'Avocet Road',
        'co' => 'Copstone',
        'cn' => 'Crediton',
        'hr' => 'Heron Road',
        'ht' => 'Honiton',
        'ie' => 'Ivybridge',
        'kn' => 'Kingsteignton',
        'mn' => 'Merton',
        'on' => 'Okehampton',
        'rq' => 'Rydon Quarry',
        'sm' => 'South Molton',
        'tk' => 'Tavistock',
        'tn' => 'Tiverton',
        'tr' => 'Torr',
        'ae' => 'Andover',
        'bw' => 'Bishops Waltham',
        'bs' => 'Broadmarsh',
        'hk' => 'Hook',
        'pd' => 'Petersfield',
        'to' => 'Totton',
        'hp' => 'Hinkley Point',
        'sd' => 'Sandford',
        'dn' => 'Deddington',
        'dt' => 'Drayton',
        'mc' => 'Milton Common',
        'od' => 'Oxford',
        'we' => 'Woodcote',
        'ph' => 'Peterborough',
        'dl' => 'Dunball',
        'ed' => 'Exford',
        'fe' => 'Frome',
        'gy' => 'Glastonbury',
        'md' => 'Minehead',
        'po' => 'Priorswood',
        'ta' => 'Taunton',
        'yl' => 'Yeovil',
        'a8' => 'A428',
        'sk' => 'Snaresbrook',
        'gr' => 'Gloucester',
        're' => 'Redbridge',
        'sc' => 'South Croydon',
        'mo' => 'Merrow O&M',
        'me' => 'Merrow External',
    ],

    'userAccessibleRegionsForSelect' => [
        'all' => 'All'
    ],

    'userAccessibleRegionsForSelectSample' => [
        'Bristol' => 'bl',
        'City of London' => 'cl',
        'Essex' => 'ex',
        'East Kent' => 'ek',
        'Kent' => 'kt',
        'West Kent' => 'wk',
        'Northwood' => 'nd',
        'Motherwell' => 'ml',
        'Woking' => 'wg',
        'Cambridge' => 'ce',
        'Ely' => 'ey',
        'Huntingdon' => 'hn',
        'March' => 'mh',
        'Whittlesford' => 'wd',
        'Avocet Road' => 'ar',
        'Copstone' => 'co',
        'Crediton' => 'cn',
        'Heron Road' => 'hr',
        'Honiton' => 'ht',
        'Ivybridge' => 'ie',
        'Kingsteignton' => 'kn',
        'Merton' => 'mn',
        'Okehampton' => 'on',
        'Rydon Quarry' => 'rq',
        'South Molton' => 'sm',
        'Tavistock' => 'tk',
        'Tiverton' => 'tn',
        'Torr' => 'tr',
        'Andover' => 'ae',
        'Bishops Waltham' => 'bw',
        'Broadmarsh' => 'bs',
        'Hook' => 'hk',
        'Petersfield' => 'pd',
        'Totton' => 'to',
        'Hinkley Point' => 'hp',
        'Sandford' => 'sd',
        'Deddington' => 'dn',
        'Drayton' => 'dt',
        'Milton Common' => 'mc',
        'Oxford' => 'od',
        'Woodcote' => 'we',
        'Peterborough' => 'ph',
        'Dunball' => 'dl',
        'Exford' => 'ed',
        'Frome' => 'fe',
        'Glastonbury' => 'gy',
        'Minehead' => 'md',
        'Priorswood' => 'po',
        'Taunton' => 'ta',
        'Yeovil' => 'yl',
        'A428' => 'a8',
        'Snaresbrook' => 'sk',
        'Gloucester' => 'gr',
        'Redbridge' => 're',
        'South Croydon' => 'sc',
        'mo' => 'Merrow O&M',
        'me' => 'Merrow External',
    ],
];
